# Generated by Django 5.0.7 on 2024-09-28 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_complaint_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_complaints', models.PositiveIntegerField()),
                ('badge_icon', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.badge'),
        ),
    ]
