# Generated by Django 5.0.7 on 2024-09-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_badge_customuser_current_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('AWAITING_APPROVAL', 'AWAITING APPROVAL'), ('OPEN', 'OPEN'), ('AUTO_CLOSED', 'AUTO CLOSED'), ('RESOLVED', 'RESOLVED'), ('REOPENED', 'REOPENED')], default='AWAITING_APPROVAL', max_length=20),
        ),
    ]
