# Generated by Django 5.0.7 on 2024-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('AWAITING_APPROVAL', 'AWAITING APPROVAL'), ('OPEN', 'OPEN'), ('AUTO_CLOSED', 'AUTO CLOSED'), ('RESOLVED', 'RESOLVED'), ('REOPENED', 'REOPENED'), ('FORCE_CLOSED', 'FORCE CLOSED')], default='AWAITING_APPROVAL', max_length=20),
        ),
    ]
