# Generated by Django 5.0.7 on 2024-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_city_complaint_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
