# Generated by Django 5.0.7 on 2024-11-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_complaint_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reopened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
