# Generated by Django 5.0.7 on 2024-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_complaint_reopened'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='posted_to_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
