# Generated by Django 5.0.7 on 2024-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
