# Generated by Django 5.0.7 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
