# Generated by Django 5.0.7 on 2024-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_complaint_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
