# Generated by Django 5.0.7 on 2024-12-29 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_complaint_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='APPROVED', max_length=20)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.complaint')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
