# Generated by Django 5.0.7 on 2024-12-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_moderatorapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorapproval',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='APPROVED', max_length=20),
        ),
    ]
