# Generated by Django 5.0.7 on 2024-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_moderatorapproval_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disabled',
            field=models.CharField(choices=[('FALSE', 'FALSE'), ('TRUE', 'TRUE')], default='FALSE', max_length=20),
        ),
    ]
