# Generated by Django 5.0.7 on 2024-12-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_moderatorapproval_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorapproval',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
