# Generated by Django 5.0.7 on 2024-12-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_moderatorapproval_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorapproval',
            name='action',
            field=models.CharField(choices=[('APPROVED_BY_MOD', 'APPROVED_BY_MOD'), ('APPROVED_BY_AI', 'APPROVED_BY_AI'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED'), ('DISABLE_USER', 'DISABLE_USER'), ('ENABLE_USER', 'ENABLE_USER')], default='APPROVED', max_length=20),
        ),
    ]
