# Generated by Django 5.0.7 on 2024-12-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_moderatorapproval_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocloseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='posted_to_twitter',
        ),
        migrations.AlterField(
            model_name='moderatorapproval',
            name='action',
            field=models.CharField(choices=[('APPROVED_BY_MOD', 'APPROVED_BY_MOD'), ('APPROVED_BY_AI', 'APPROVED_BY_AI'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED'), ('DISABLE_USER', 'DISABLE_USER'), ('ENABLE_USER', 'ENABLE_USER')], default='APPROVED_BY_MOD', max_length=20),
        ),
    ]
