# Generated by Django 5.0.7 on 2024-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_complaint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
