# Generated by Django 5.0.7 on 2024-12-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
