# Generated by Django 5.0.7 on 2025-01-02 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_complaint_image_alter_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 21, 0, 0)),
            preserve_default=False,
        ),
    ]
