# Generated by Django 5.0.7 on 2025-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_customuser_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='posted_on_x',
            field=models.BooleanField(default=False),
        ),
    ]
